---
- name: Update all installed packages
  community.general.pacman:
    upgrade: true
  become: true

# Install openssh client
- name: Install ssh - Archlinux
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - base-devel
    - openssh
    - yay
