---
- name: Update all installed packages
  community.general.pacman:
    upgrade: true
  become: true

# Install openssh client
- name: Install additional packages - Archlinux
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - base-devel
    - openssh
    - yay
    - fd
    - the_silver_searcher

- name: Install additional packages with yay
  ansible.builtin.command: "yay -Syu --noconfirm --needed {{ item }}"
  with_items:
    - maestral
    - maestral-git
    - ghq
    - hugo
