---
# tasks file for roles/gnome
- name: Install Ansible community.general
  shell: ansible-galaxy collection install community.general
  register: general_install
  changed_when: 'general_install.stdout is not search("Nothing to do. All requested collections are already installed.")'

- name: Create background image folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/backgrounds"
    state: directory
    mode: "0755"

# Copy desktop wallpaper
- name: Copy desktop wallpaper to pictures
  ansible.builtin.copy:
    src: jeremy-bishop-h7bQ8VEZtws-unsplash.jpg
    dest: "{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.jpg"

# Activate wallpaper
- name: Set wallpaper image
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "\"file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.jpg\""

- name: Set wallpaper image dark
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "\"file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.jpg\""

- name: Activate wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "\"file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.jpg\""

- name: Activate compose key, enable Euro sign on e and disable caps lock
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:none', 'eurosign:e', 'compose:ralt']"

- name: Print key starts flameshot
  block:
    - name: Remove default mapping
      community.general.dconf:
        key: "/org/gnome/shell/keybindings/show-screenshot-ui"
        value: "@as []"
    - name: Add Value Print
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'Print'"
    - name: Set flameshot command
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'/usr/bin/flameshot gui'"
    - name: Set Custom name
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Flameshot'"
    - name: Add custom custom-keybindings
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

    - name: Set QT_QPA_PLATFORM in /etc/environment
      lineinfile:
        path: "/etc/environment"
        state: present
        regexp: "^QT_QPA_PLATFORM="
        line: "QT_QPA_PLATFORM=xcb flameshot"
      become: true

- name: Disable night light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: false

