---
# tasks file for roles/prerequisits
#
- name: Update all installed packages
  community.general.pacman:
    upgrade: true
  become: true
  when:
    - ansible_os_family == "Archlinux"

- name: Install all needed packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - texlive
    - texlive-langgerman
    - texlive-hyphen-german

- name: Install pympress
  shell: yay -Syu --noconfirm --needed python-pympress
  register: result
  changed_when: 'result.stdout is not search(" there is nothing to do")'
